version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - npm run build
      - ls -al  # ✅ Debug: check what folders/files exist after build

artifacts:
  base-directory: build  # ✅ This assumes your build output goes to `build/` (e.g., React)
  files:
    - '**/*'
